=== adritell/Lenguaje-Marcas/Tema1/discografica.dtd
<!ELEMENT discografica (disco,interprete,pista)>
<!ELEMENT disco (titulo,interpretes,numero_pistas)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT interpretes (#PCDATA)>
<!ELEMENT numero_pistas (#PCDATA)>
<!ELEMENT interprete (nombre,apellidos,rol*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT rol (#PCDATA)>
<!ELEMENT pista (nombre,duracion)>
<!ELEMENT duracion (#PCDATA)>

=== adritell/Lenguaje-Marcas/Tema1/discografica_ext.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE discografica SYSTEM "discografica.dtd">
<discografica>
    <disco>
        <titulo></titulo>
        <interpretes></interpretes>
        <numero_pistas></numero_pistas>
    </disco>
    <interprete>
        <nombre></nombre>
        <apellidos></apellidos>
        <rol></rol>
    </interprete>
    <pista>
        <nombre></nombre>
        <duracion></duracion>
    </pista>
</discografica>
