=== adritell/Lenguaje-Marcas/Tema1/matricula.dtd
<!ELEMENT matricula (personal,pago)>
<!ELEMENT personal (DNI,nombre,titulacion,curso_academico,domicilios+)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT curso_academico (#PCDATA)>
<!ELEMENT domicilios (domicilio+)>
<!ELEMENT domicilio (nombre)>
<!ELEMENT pago (tipo_matricula)>
<!ELEMENT tipo_matricula (#PCDATA)>

=== adritell/Lenguaje-Marcas/Tema1/matricula_ext.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE matricula SYSTEM "matricula.dtd">
<matricula>
    <personal>
        <DNI></DNI>
        <nombre></nombre>
        <titulacion></titulacion>
        <curso_academico></curso_academico>
        <domicilios>
            <domicilio>
                <nombre></nombre>
            </domicilio>
            <domicilio>
                <nombre></nombre>
            </domicilio>
        </domicilios>
    </personal>
    <pago>
        <tipo_matricula></tipo_matricula>
    </pago>
</matricula>
